ALTER TABLE animal DROP CONSTRAINT FKanimal671527;
ALTER TABLE animal_color DROP CONSTRAINT FKanimal_col636172;
ALTER TABLE animal_color DROP CONSTRAINT FKanimal_col508029;
ALTER TABLE animal_for_sale DROP CONSTRAINT FKanimal_for544370;
ALTER TABLE parents DROP CONSTRAINT FKparents456775;
ALTER TABLE parents DROP CONSTRAINT FKparents161176;
ALTER TABLE animals_photos DROP CONSTRAINT FKanimals_ph742258;
ALTER TABLE animals_photos DROP CONSTRAINT FKanimals_ph965934;
DROP TABLE IF EXISTS Admin CASCADE;
DROP TABLE IF EXISTS color CASCADE;
DROP TABLE IF EXISTS species CASCADE;
DROP TABLE IF EXISTS animal CASCADE;
DROP TABLE IF EXISTS photos CASCADE;
DROP TABLE IF EXISTS animal_for_sale CASCADE;
DROP TABLE IF EXISTS animal_color CASCADE;
DROP TABLE IF EXISTS parents CASCADE;
DROP TABLE IF EXISTS animals_photos CASCADE;
CREATE TABLE Admin (id SERIAL NOT NULL, login varchar(30) NOT NULL UNIQUE, password varchar(255) NOT NULL, is_active bool NOT NULL, PRIMARY KEY (id));
CREATE TABLE color (id SERIAL NOT NULL, name varchar(255) NOT NULL UNIQUE, PRIMARY KEY (id));
CREATE TABLE species (id SERIAL NOT NULL, name varchar(255) NOT NULL UNIQUE, PRIMARY KEY (id));
CREATE TABLE animal (id SERIAL NOT NULL, description int4 NOT NULL, sex int2 NOT NULL, date_of_birth date NOT NULL, species_id int4 NOT NULL, PRIMARY KEY (id));
CREATE TABLE photos (id SERIAL NOT NULL, photo_path varchar(255) NOT NULL UNIQUE, PRIMARY KEY (id));
CREATE TABLE animal_for_sale (animal_id int4 NOT NULL, price int4 NOT NULL, reservation_status varchar(255) DEFAULT 'Niezarezerwowany' NOT NULL, PRIMARY KEY (animal_id));
CREATE TABLE animal_color (animal_id int4 NOT NULL, color_id int4 NOT NULL, PRIMARY KEY (animal_id, color_id));
CREATE TABLE parents (parent_id int4 NOT NULL UNIQUE, animal_id int4 NOT NULL UNIQUE, PRIMARY KEY (parent_id, animal_id));
CREATE TABLE animals_photos (animal_id int4 NOT NULL, photos_id int4 NOT NULL, PRIMARY KEY (animal_id, photos_id));
ALTER TABLE animal ADD CONSTRAINT FKanimal671527 FOREIGN KEY (species_id) REFERENCES species (id);
ALTER TABLE animal_color ADD CONSTRAINT FKanimal_col636172 FOREIGN KEY (animal_id) REFERENCES animal (id);
ALTER TABLE animal_color ADD CONSTRAINT FKanimal_col508029 FOREIGN KEY (color_id) REFERENCES color (id);
ALTER TABLE animal_for_sale ADD CONSTRAINT FKanimal_for544370 FOREIGN KEY (animal_id) REFERENCES animal (id);
ALTER TABLE parents ADD CONSTRAINT FKparents456775 FOREIGN KEY (animal_id) REFERENCES animal_for_sale (animal_id);
ALTER TABLE parents ADD CONSTRAINT FKparents161176 FOREIGN KEY (parent_id) REFERENCES animal (id);
ALTER TABLE animals_photos ADD CONSTRAINT FKanimals_ph742258 FOREIGN KEY (animal_id) REFERENCES animal (id);
ALTER TABLE animals_photos ADD CONSTRAINT FKanimals_ph965934 FOREIGN KEY (photos_id) REFERENCES photos (id);
