spring:
  liquibase:
      enabled: false
      change-log: classpath:/db/master.xml
      contexts: dev
  # Hibernate
  jpa:
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          auto: create-drop
          import_files: /db/data.sql


  # Database
  datasource:
    url: jdbc:postgresql://localhost:5432/Tropiria
    username: postgres
    password: Q@werty
  data:
    jpa:
      repositories:
        bootstrap-mode:
  # Server
server:
  port: 8080
  servlet:
    context-path: /tropiria/api/v1

    # Logging
logging:
  level:
    org:
      springframework: debug

